import { useState, useEffect } from "react";
import { Sparkles, Layers, Search } from "lucide-react";
import { InsightList } from "@/components/insights/InsightList";
import { PageTransition } from "@/components/ui/page-transition";
import { PageHeader } from "@/components/ui/page-header";
import { InfoNote } from "@/components/ui/info-note";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useClusters } from "@/hooks/useClusters";
import { useDebounce } from "@/hooks/useDebounce";
import { getClusterDisplayName } from "@/lib/utils";
import { DEFAULT_PAGE_SIZE } from "@/constants";

export const InsightsPage = () => {
  const [selectedClusterId, setSelectedClusterId] = useState<
    string | undefined
  >();
  const [searchQuery, setSearchQuery] = useState("");
  const [offset, setOffset] = useState(0);
  const debouncedSearch = useDebounce(searchQuery);
  const limit = DEFAULT_PAGE_SIZE;
  const { data: clustersData } = useClusters();

  useEffect(() => {
    const id = setTimeout(() => setOffset(0), 0);
    return () => clearTimeout(id);
  }, [selectedClusterId, debouncedSearch]);

  const handlePageChange = (newPage: number) => {
    setOffset((newPage - 1) * limit);
  };

  return (
    <PageTransition>
      <div className="space-y-6">
        <PageHeader
          title="Insights"
          description="AI-generated insights from your document clusters"
          icon={Sparkles}
          iconColor="text-violet-600 dark:text-violet-400"
        />

        <InfoNote variant="tip">
          <p>
            <strong>AI-Generated Insights:</strong> These insights are
            automatically generated by analyzing patterns, trends, and
            relationships within your document clusters. The AI identifies key
            themes, correlations, and notable observations that might not be
            immediately obvious.
          </p>
          <p className="mt-2 text-xs">
            <strong>Confidence Scores:</strong> Each insight includes a
            confidence percentage indicating how certain the AI model is about
            the observation. Higher confidence (80%+) suggests more reliable
            insights. Use the search and cluster filters to find insights
            relevant to your interests.
          </p>
        </InfoNote>

        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 animate-in fade-in-0 slide-in-from-top-2 duration-300">
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Sparkles className="w-4 h-4 text-violet-500" />
            <span>Powered by AI analysis</span>
          </div>

          <div className="flex items-center gap-3">
            <div className="relative flex-1 sm:flex-initial">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                type="text"
                placeholder="Search insights..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9 w-full sm:w-[250px]"
              />
            </div>
            <Label
              htmlFor="cluster-filter"
              className="text-sm text-muted-foreground whitespace-nowrap hidden sm:block"
            >
              Filter by cluster:
            </Label>
            <Select
              value={selectedClusterId || "all"}
              onValueChange={(value) =>
                setSelectedClusterId(value === "all" ? undefined : value)
              }
            >
              <SelectTrigger
                id="cluster-filter"
                className="w-full sm:w-[200px]"
              >
                <SelectValue placeholder="All clusters" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Clusters</SelectItem>
                {clustersData?.clusters.map((cluster) => (
                  <SelectItem key={cluster.id} value={cluster.id}>
                    <div className="flex items-center gap-2">
                      <Layers className="w-3.5 h-3.5" />
                      <span>{getClusterDisplayName(cluster.id)}</span>
                    </div>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>

        <InsightList
          clusterId={selectedClusterId}
          selectedClusterName={
            selectedClusterId
              ? clustersData?.clusters.find((c) => c.id === selectedClusterId)
                ? getClusterDisplayName(selectedClusterId)
                : getClusterDisplayName(selectedClusterId)
              : undefined
          }
          searchQuery={debouncedSearch}
          limit={limit}
          offset={offset}
          onPageChange={handlePageChange}
        />
      </div>
    </PageTransition>
  );
};
