export const TRENDING_HOT_THRESHOLD = 0.9;
export const REFETCH_ACTIVE_INGEST_MS = 5000;
export const REFETCH_UNPROCESSED_DOCS_MS = 10000;
export const DEFAULT_PAGE_SIZE = 50;
export const ANOMALIES_TIMELINE_LIMIT = 1000;
export const DOCUMENTS_DISTRIBUTION_LIMIT = 5000;
export const CLUSTERS_LIST_LIMIT = 2000;
export const INSIGHTS_LIST_LIMIT = 1000;
